name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/checkout@v1

    - run: mkdir -p Prajakta/

    - run: echo Prajaktahello > Prajakta/demo-0.0.1-SNAPSHOT.jar

    - uses: actions/upload-artifact@v1
      with:
       name: demo-0.0.1-SNAPSHOT
       path: Prajakta/

  
