name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml
      
    - uses: actions/checkout@v1

    - run: mkdir -p target/

    - run: echo Prajaktahello > target/demo-0.0.1-SNAPSHOT.jar

    - uses: actions/upload-artifact@v1
      with:
       name: demo-0.0.1-SNAPSHOT.jar
       path: target/

  
